---
title: Insights from COVID-19 Datasets Using R
author: Jojo Abalos
date: '2020-04-19'
slug: insights-from-covid-19-datasets-using-r
categories:
  - R
tags:
  - R
  - R Studio
  - COVID-19
  - COVID
subtitle: ''
summary: ''
authors: []
lastmod: '2020-04-19T16:39:06+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r echo=FALSE, message=FALSE,warning=FALSE}
# these libraries need to be loaded
library(utils)
library(tidyverse)
library(ggthemes)
library(plotly)
```


```{r echo=FALSE}
# read the Dataset sheet into “R”. The dataset will be called "data".
ECDC <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM")
JHU <- read.csv("https://raw.githubusercontent.com/datasets/covid-19/master/data/countries-aggregated.csv",na.strings = "", fileEncoding = "UTF-8-BOM")

# reformat date column
ECDC$dateRep <- as.Date(ECDC$dateRep, format = "%d/%m/%Y")
JHU$Date <- as.Date(JHU$Date)
```



```{r echo=FALSE}
JHU.TOP12 <- JHU %>%
  filter(Date == max(Date)) %>% 
  arrange(desc(Confirmed)) %>%   
  top_n(n=12,wt=Confirmed)

JHU.TOP12.SMRY <- JHU %>% 
  filter(Country %in% JHU.TOP12$Country) %>%
  group_by(Country) %>% 
  mutate(ConfirmedPerDay = Confirmed-lag(Confirmed,default = 0),
         RecoveredPerDay = Recovered-lag(Recovered,default = 0),
         DeathsPerDay = Deaths-lag(Deaths,default = 0)) %>% 
  mutate(FatalityRatePct = Deaths/Confirmed*100,
         RecoveryRatePct = Recovered/Confirmed*100) 
```

***

```{r echo=FALSE}
p1 <- ggplot(JHU.TOP12.SMRY) +
 aes(x = Date, y = Confirmed, fill = Country, colour = Country) +
 labs(x = "", y = "", title = "Covid-19 Top 12 Countries by Cumulative Cases", subtitle = "Jojo Abalos", 
      caption = "Data: Johns Hopkins University; Visuals: R/RStudio") +
 geom_line(size = 1) +
 scale_fill_hue() +
 scale_color_hue() +
 theme_pander(bc="snow2") +
 theme(plot.margin=unit(c(1.5,0,0,0),"cm"))
```



```{r fig.width=4, fig.height=8, message=FALSE, echo=FALSE}
plotly::ggplotly(p1) %>%
  layout(title = list(text = paste0('Covid-19 Top 12 Countries by Cumulative Cases',
                                    '<br>',
                                    '<sup>',
                                    'Data from Johns Hopkins University; Visuals using R/RStudio/Plotly; R Scripts by Jojo Abalos',
                                    '</sup>')))
```

****

```{r echo=FALSE}
p2 <- ggplot(JHU.TOP12.SMRY) +
 aes(x = Date, y = Confirmed, fill = Country, colour = Country) +
 facet_wrap(vars(Country)) + 
 labs(x = "", y = "", title = "Covid-19 Top 12 Countries by Cumulative Cases", subtitle = "Jojo Abalos", 
      caption = "Data: Johns Hopkins University; Visuals: R/RStudio") +
 geom_line(size=1) +
 scale_fill_hue() +
 scale_color_hue() +
 theme_pander(bc="snow2") +
 theme(plot.margin=unit(c(1.5,0,0,0),"cm"))
```


```{r fig.width=6, fig.height=8, message=FALSE, echo=FALSE}
plotly::ggplotly(p2) %>%
  layout(title = list(text = paste0('Covid-19 Top 12 Countries by Cumulative Cases',
                                    '<br>',
                                    '<sup>',
                                    'Data from Johns Hopkins University; Visuals using R/RStudio/Plotly; R Scripts by Jojo Abalos',
                                    '</sup>')))
```

***

```{r echo=FALSE}
p3 <- ggplot(JHU.TOP12.SMRY) +
 aes(x = Date, y = ConfirmedPerDay, fill = Country, colour = Country) +
 labs(x = "", y="", title = "Covid-19 Top 12 Countries by Confirmed Cases Per Day", subtitle = "Jojo Abalos", 
      caption = "Data: Johns Hopkins University; Visuals: R/RStudio") +
 geom_line(size = 1) +
 scale_fill_hue() +
 scale_color_hue() +
 theme_pander(bc="snow2") +
 theme(plot.margin=unit(c(1.5,0,0,0),"cm"))
```

```{r fig.width=4, fig.height=8, message=FALSE, echo=FALSE}
plotly::ggplotly(p3) %>%
  layout(title = list(text = paste0('Covid-19 Top 12 Countries by Cumulative Cases',
                                    '<br>',
                                    '<sup>',
                                    'Data from Johns Hopkins University; Visuals using R/RStudio/Plotly; R Scripts by Jojo Abalos',
                                    '</sup>')))
```

***

```{r echo=FALSE}
p4 <- ggplot(JHU.TOP12.SMRY) +
 aes(x = Date, y = ConfirmedPerDay, fill = Country, colour = Country) +
 facet_wrap(vars(Country)) + 
 labs(x = "", y="", title = "Covid-19 Top 12 Countries by Confirmed Cases Per Day", subtitle = "Jojo Abalos", 
      caption = "Data: Johns Hopkins University; Visuals: R/RStudio") +
 geom_line(size=1) +
 scale_fill_hue() +
 scale_color_hue() +
 theme_pander(bc="snow2") +
 theme(plot.margin=unit(c(1.5,0,0,0),"cm"))
```


```{r fig.width=6, fig.height=8, message=FALSE, echo=FALSE}
plotly::ggplotly(p4) %>%
  layout(title = list(text = paste0('Covid-19 Top 12 Countries by Cumulative Cases',
                                    '<br>',
                                    '<sup>',
                                    'Data from Johns Hopkins University; Visuals using R/RStudio/Plotly; R Scripts by Jojo Abalos',
                                    '</sup>')))
```

***


